name: Build Rust project
on: [push]
jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose --release --target=x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v3
      with:
        name: fy.exe
        path: target/x86_64-pc-windows-msvc/release/fanyi.exe
